### ISSUE TITLE
Change kappnav CRD group from *.k8s.io

### ISSUE THREAD

**Issue by cvignola** [kappnav/operator#17]
*.k8s.io is reserved by the kubernetes platform.  This issue will change the group value to *.kappnav.io

**Comment by cvignola** [comment]
this affects: 

1. kappnav-delete.yaml	
2. kappnav-delete-CR.yaml	
3. kappnav.yaml		
4. watches.yaml

**Comment by rlcundiff** [comment]
Susan, this is needed for the 0.1.1 release.

**Comment by susanodom** [comment]
The code change is merged using https://github.com/kappnav/operator/pull/21
